- hosts: servers
  become: true
  tasks:
    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: your_mysql_root_password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: your_wordpress_db_password
        ports:
          - "8080:80"
        volumes:
          - wordpress:/var/www/html
        restart_policy: always

    - name: Deploy MySQL container
      community.docker.docker_container:
        name: mysql
        image: mariadb:latest
        state: started
        env:
          WORDPRESS_DB_HOST: mysql_wp
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: your_wordpress_db_password
        ports:
          - "3305:3305"
        volumes:
          - db:/var/lib/mysql
        networks:
          - name: wordpress
        restart_policy: always
