- name: devops app deployment
  hosts: servers
  become: true
  any_errors_fatal: true
  vars_files:
    - "vars/vars_app.yml"
  tasks:
    - name: set nameservers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"

    - name: Install necessary packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: present
      loop: "{{ required_packages }}"

    - name: Clone Remote Git Repository
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_dest }}"
      register: git_clone
      ignore_errors: true

    - name: Go mod download and build
      command: >
        bash -c "cd {{ git_repo_dest }} && go mod download && go build -o ./app ./cmd"
      become: true

    - name: Start the server
      command: "{{ git_repo_dest }}/app"
      become: true
