- name: devops app deployment
  hosts: servers
  become: true
  any_errors_fatal: true
  vars_files:
    - "vars/vars_app.yml"
  tasks:
    - name: include vault
      ansible.builtin.include_vars:
        file: "vars/vars_secrets.yml"

    - name: set nameservers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"

    - name: Install necessary packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: present
      loop: "{{ required_packages }}"

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker Compose is executable
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: u+x
        owner: root
        group: root
        state: link
        src: /usr/bin/docker-compose

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /var/www/docker-compose
        state: directory
        mode: "0755"

    - name: Copy docker-compose.yml to the target machine
      ansible.builtin.copy:
        src: "../docker-compose/docker-compose.yml"
        dest: "/var/www/docker-compose/docker-compose.yml"
        mode: "0644"

    - name: Create letsencrypt directory
      file:
        path: /var/www/docker-compose/letsencrypt
        state: directory

    #- name: Create Docker network
    #  ansible.builtin.command:
    #    cmd: docker network create internal

    - name: Deploy Docker Containers
      community.docker.docker_compose:
        project_src: "/var/www/docker-compose/"
        state: present
        build: yes
        restarted: yes
